- .github/workflows/CI.yaml
- .gitignore
- LICENSE
- README.md
- devtools/conda-envs/test_env.yaml
- docs/conf.py
- pyvpt2/constants.py
- pyvpt2/quartic.py
- pyvpt2/tests/test_pyvpt2.py
- pyvpt2/vpt2.py
> Pull updates

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
- pyvpt2/tests/test_h2o_snowflake.py
> Add QCFractal snowflake test

- .gitignore
- devtools/conda-envs/test_env.yaml
- pyvpt2/quartic.py
- pyvpt2/tests/test_h2o_multilevel.py
- pyvpt2/vpt2.py
> October updates

- devtools/conda-envs/test_env.yaml
> pin psi4 version

- .github/workflows/CI.yaml
- LICENSE
- README.md
- devtools/conda-envs/test_env.yaml
- docs/conf.py
- pyvpt2/quartic.py
- pyvpt2/tests/test_h2o_snowflake.py
Bump psi4 version back to current upstream.
> Psi4 1.7 updates

- .github/workflows/CI.yaml
- README.md
- pyvpt2/fermi_solver.py
- pyvpt2/tests/test_fermi_solver.py
- pyvpt2/tests/test_polyad.py
- pyvpt2/vpt2.py
- Add interaction dataclass rather than using dictionaries
- Attempt mamba?
> Add interaction dataclass

- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
Pin QCFractal version to fix CI.
> Pin QCFractal version

- pyvpt2/result.py
- pyvpt2/tests/test_h2co.py
- pyvpt2/tests/test_h2o.py
- pyvpt2/tests/test_h2o_cbs.py
- pyvpt2/tests/test_h2o_multilevel.py
- pyvpt2/tests/test_h2o_snowflake.py
- pyvpt2/tests/test_hf.py
- pyvpt2/vpt2.py
> Add results data class

- pyvpt2/vpt2.py
Fix step-sizing issues for very low frequency modes
> Fix low frequency step sizing

- devtools/conda-envs/test_env_nightly.yaml
Pull nightly psi4 from conda-forge
> CI: test psi4 from conda-forge

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
- pyvpt2/__init__.py
- pyvpt2/quartic.py
- pyvpt2/tests/test_h2o_snowflake.py
- pyvpt2/vpt2.py
Updates for compatibility with psi4 1.8 and qcfractal v0.50b10
> QCFractal updates

- README.md
- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
> Pin pydantic version

- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
- pyproject.toml
> pydantic v2

- .github/workflows/CI.yaml
`provision-with-micromamba` is deprecated. update to `setup-micromamba`
> migrate to setup-micromamba

- devtools/conda-envs/test_env_stable.yaml
> try qcfractal v0.50

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
> CI matrix updates

- pyvpt2/task_planner.py
> Fix log printing in task_planner.py

- pyvpt2/vpt2.py
> Fix intensity key in process_harmonic()

- .github/workflows/CI.yaml
- docs/index.md
- docs/tutorial.md
- mkdocs.yml
> Add documentation

- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
> Update test environments

- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/test_env_nightly.yaml
- devtools/conda-envs/test_env_stable.yaml
- docs/index.md
- pyvpt2/quartic.py
> Unpin pydantic version

- docs/index.md
> update doc link

- .github/workflows/publish_pypi.yaml
> Add publish to PyPI CD workflow

- pyvpt2/__init__.py
> Add runtime version attribute

- pyvpt2/quartic.py
- pyvpt2/tests/test_h2o.py
- pyvpt2/tests/test_h2o_snowflake.py
- pyvpt2/vpt2.py
> Add larger findif stencil

- pyvpt2/vpt2.py
> Better kwarg case handling

- pyvpt2/quartic.py
> Fix large stencil bug
